BEGIN;
CREATE SCHEMA IF NOT EXISTS zhixu;
SET LOCAL search_path = zhixu, pg_catalog;
CREATE TABLE IF NOT EXISTS "attempts" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"learner" text NOT NULL,
	"request_id" text NOT NULL,
	"question_id" text NOT NULL,
	"answer" text NOT NULL,
	"correct" bigint NOT NULL,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_attempts_learner_question" ON "attempts" ("learner","question_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_attempts_learner_request" ON "attempts" ("learner","request_id");
CREATE TABLE IF NOT EXISTS "tutor_limits" (
	"bucket" text PRIMARY KEY NOT NULL,
	"window" bigint NOT NULL,
	"used" bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "evidence_baselines" (
	"learner" text PRIMARY KEY NOT NULL,
	"model_version" text NOT NULL,
	"through_seq" bigint NOT NULL,
	"summary" text NOT NULL,
	"created_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "evidence_commands" (
	"learner" text NOT NULL,
	"command_id" text NOT NULL,
	"hash" text NOT NULL,
	"response" text DEFAULT '{}' NOT NULL,
	"guard" bigint DEFAULT 1 NOT NULL,
	"created_at" bigint NOT NULL,
	PRIMARY KEY("learner", "command_id"),
	CONSTRAINT "evidence_command_guard" CHECK("evidence_commands"."guard" = 1)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "evidence_deletions" (
	"learner" text PRIMARY KEY NOT NULL,
	"requested_at" bigint NOT NULL,
	"completed_at" bigint
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "evidence_events" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"learner" text NOT NULL,
	"command_id" text NOT NULL,
	"kind" text NOT NULL,
	"topic" text NOT NULL,
	"presentation_id" text,
	"payload" text NOT NULL,
	"created_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_events_learner_seq" ON "evidence_events" ("learner","seq");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_events_command_kind" ON "evidence_events" ("learner","command_id","kind");--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "evidence_presentations" (
	"id" text PRIMARY KEY NOT NULL,
	"learner" text NOT NULL,
	"item_id" text NOT NULL,
	"item_version" bigint NOT NULL,
	"topic" text NOT NULL,
	"purpose" text NOT NULL,
	"family_id" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"assistance" bigint DEFAULT 0 NOT NULL,
	"created_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_presentations_learner" ON "evidence_presentations" ("learner","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_presentations_active" ON "evidence_presentations" ("learner") WHERE "evidence_presentations"."status" = 'active';--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "evidence_profiles" (
	"id" text PRIMARY KEY NOT NULL,
	"recovery_hash" text,
	"created_at" bigint NOT NULL,
	"deleted_at" bigint
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "evidence_profiles_recovery_hash_unique" ON "evidence_profiles" ("recovery_hash");--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "evidence_snapshots" (
	"learner" text PRIMARY KEY NOT NULL,
	"model_version" text NOT NULL,
	"through_seq" bigint NOT NULL,
	"summary" text NOT NULL,
	"updated_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tutor_reservations" (
	"id" text PRIMARY KEY NOT NULL,
	"learner" text NOT NULL,
	"status" text NOT NULL,
	"created_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_tutor_reservations_created" ON "tutor_reservations" ("created_at");
ALTER TABLE "evidence_profiles" ADD COLUMN IF NOT EXISTS "legacy_through" bigint DEFAULT 0 NOT NULL;
ALTER TABLE "evidence_profiles" ADD COLUMN IF NOT EXISTS "student_name" text DEFAULT '' NOT NULL;
CREATE TABLE IF NOT EXISTS "learning_journeys" (
	"learner" text NOT NULL,
	"lesson" text NOT NULL,
	"revision" bigint DEFAULT 0 NOT NULL,
	"state" text NOT NULL,
	"updated_at" bigint NOT NULL,
	PRIMARY KEY("learner", "lesson")
);

CREATE TABLE IF NOT EXISTS "tutor_conversations" (
	"id" text PRIMARY KEY NOT NULL,
	"learner" text NOT NULL,
	"lesson_id" text NOT NULL,
	"resource_id" text NOT NULL,
	"context_version" text NOT NULL,
	"context_snapshot" text NOT NULL,
	"revision" bigint DEFAULT 0 NOT NULL,
	"pending_request_id" text,
	"pending_at" bigint,
	"deleted_at" bigint,
	"created_at" bigint NOT NULL,
	"updated_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_course_conversation_active" ON "tutor_conversations" ("learner","lesson_id","resource_id") WHERE "tutor_conversations"."deleted_at" IS NULL;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tutor_messages" (
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"id" text NOT NULL,
	"learner" text NOT NULL,
	"conversation_id" text NOT NULL,
	"request_id" text NOT NULL,
	"request_hash" text NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"action" text NOT NULL,
	"status" text NOT NULL,
	"reply" text,
	"created_at" bigint NOT NULL,
	CONSTRAINT "course_message_role" CHECK("tutor_messages"."role" IN ('user','assistant')),
	CONSTRAINT "course_message_status" CHECK("tutor_messages"."status" IN ('pending','completed','failed','unknown'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "tutor_messages_id_unique" ON "tutor_messages" ("id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_course_turn_role" ON "tutor_messages" ("conversation_id","request_id","role");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_course_messages" ON "tutor_messages" ("conversation_id","learner","seq");

CREATE OR REPLACE FUNCTION zhixu.json_extract(document text, path text) RETURNS text
LANGUAGE sql IMMUTABLE AS 'SELECT document::jsonb #>> string_to_array(substr(path, 3), ''.'')';
CREATE OR REPLACE FUNCTION zhixu.json_set(document text, path text, value anyelement) RETURNS text
LANGUAGE sql IMMUTABLE AS 'SELECT jsonb_set(document::jsonb, string_to_array(substr(path, 3), ''.''), to_jsonb(value), true)::text';
REVOKE ALL ON SCHEMA zhixu FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA zhixu TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA zhixu TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA zhixu TO service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA zhixu TO service_role;
CREATE OR REPLACE FUNCTION public.zhixu_batch(statements jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY INVOKER SET search_path = zhixu, pg_catalog
AS $body$
DECLARE statement text; records jsonb; result jsonb := '[]'::jsonb;
BEGIN
  IF jsonb_typeof(statements) <> 'array' OR jsonb_array_length(statements) > 100 THEN
    RAISE EXCEPTION 'Invalid batch';
  END IF;
  FOR statement IN SELECT jsonb_array_elements_text(statements) LOOP
    IF statement ~* '^\s*SELECT\s' THEN
      EXECUTE 'SELECT coalesce(jsonb_agg(to_jsonb(q)), ''[]''::jsonb) FROM (' || statement || ') q' INTO records;
    ELSIF statement ~* '^\s*(INSERT|UPDATE|DELETE)\s' THEN
      IF statement !~* '\mRETURNING\M' THEN statement := statement || ' RETURNING *'; END IF;
      EXECUTE 'WITH changed AS (' || statement || ') SELECT coalesce(jsonb_agg(to_jsonb(changed)), ''[]''::jsonb) FROM changed' INTO records;
    ELSE RAISE EXCEPTION 'Unsupported statement';
    END IF;
    result := result || jsonb_build_array(jsonb_build_object('success', true, 'results', records,
      'meta', jsonb_build_object('changes', jsonb_array_length(records), 'last_row_id', 0)));
  END LOOP;
  RETURN result;
END $body$;
REVOKE ALL ON FUNCTION public.zhixu_batch(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.zhixu_batch(jsonb) TO service_role;
NOTIFY pgrst, 'reload schema';
COMMIT;
