import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
let sql = 'BEGIN;\nCREATE SCHEMA IF NOT EXISTS zhixu;\nSET LOCAL search_path = zhixu, pg_catalog;\n';
for (const name of readdirSync('drizzle').filter(n => n.endsWith('.sql')).sort()) {
  sql += readFileSync(`drizzle/${name}`, 'utf8').replace(/`/g, '"')
    .replace(/integer PRIMARY KEY AUTOINCREMENT NOT NULL/g, 'bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/\binteger\b/g, 'bigint')
    .replace(/CREATE (TABLE|UNIQUE INDEX|INDEX) /g, 'CREATE $1 IF NOT EXISTS ')
    .replace(/ADD "legacy_through"/, 'ADD COLUMN IF NOT EXISTS "legacy_through"') + '\n';
}
sql += `
CREATE OR REPLACE FUNCTION zhixu.json_extract(document text, path text) RETURNS text
LANGUAGE sql IMMUTABLE AS 'SELECT document::jsonb #>> string_to_array(substr(path, 3), ''.'')';
CREATE OR REPLACE FUNCTION zhixu.json_set(document text, path text, value anyelement) RETURNS text
LANGUAGE sql IMMUTABLE AS 'SELECT jsonb_set(document::jsonb, string_to_array(substr(path, 3), ''.''), to_jsonb(value), true)::text';
REVOKE ALL ON SCHEMA zhixu FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA zhixu TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA zhixu TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA zhixu TO service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA zhixu TO service_role;
CREATE OR REPLACE FUNCTION public.zhixu_batch(statements jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY INVOKER SET search_path = zhixu, pg_catalog
AS $body$
DECLARE statement text; records jsonb; result jsonb := '[]'::jsonb;
BEGIN
  IF jsonb_typeof(statements) <> 'array' OR jsonb_array_length(statements) > 100 THEN
    RAISE EXCEPTION 'Invalid batch';
  END IF;
  FOR statement IN SELECT jsonb_array_elements_text(statements) LOOP
    IF statement ~* '^\\s*SELECT\\s' THEN
      EXECUTE 'SELECT coalesce(jsonb_agg(to_jsonb(q)), ''[]''::jsonb) FROM (' || statement || ') q' INTO records;
    ELSIF statement ~* '^\\s*(INSERT|UPDATE|DELETE)\\s' THEN
      IF statement !~* '\\mRETURNING\\M' THEN statement := statement || ' RETURNING *'; END IF;
      EXECUTE 'WITH changed AS (' || statement || ') SELECT coalesce(jsonb_agg(to_jsonb(changed)), ''[]''::jsonb) FROM changed' INTO records;
    ELSE RAISE EXCEPTION 'Unsupported statement';
    END IF;
    result := result || jsonb_build_array(jsonb_build_object('success', true, 'results', records,
      'meta', jsonb_build_object('changes', jsonb_array_length(records), 'last_row_id', 0)));
  END LOOP;
  RETURN result;
END $body$;
REVOKE ALL ON FUNCTION public.zhixu_batch(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.zhixu_batch(jsonb) TO service_role;
NOTIFY pgrst, 'reload schema';
COMMIT;
`;
writeFileSync('db/cloudbase-schema.sql', sql);
